### ISSUE TITLE
Battery still not visible (but i have a lead on maybe why)

### ISSUE THREAD

**Issue by hopolapopola** [Paisseon/Vivy#1]
I've tried out Vivy on an SE 1st gen running 14.6 and odysseyra1n and a XS Max running 14.3 and Taurine, and the battery is not visible, as per other reports on reddit. However, if I enable visible battery percent, any update to the percentage will make the battery reappear. Enabling substrate compatibility mode via libhooker configurator doesn't change this behaviour. Hopefully this helps narrow down why this issue is happening ^_^

**Comment by Paisseon** [comment]
I'll look into it, thanks. Someone on Reddit says it works after a couple minutes but that's not ideal so I do want to fix it.
